### PR TITLE
Adapt to pending Enzyme breaking change

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by Red-Portal** [comment]
LGTM

**Comment by wsmoses** [comment]
@Red-Portal uh we haven't yet released 0.13 yet, just made this PR for folks to prepare

We will within a few days, but also FYI

**Comment by Red-Portal** [comment]
Ah :facepalm:

**Comment by Red-Portal** [comment]
I'll revert the revert back once the pending change happens.

**Pull request merged**
