### PR TITLE
Decrement Enzyme compatibility

### PR DESCRIPTION
**Pull request by bauglir**
It looks like the `compat` for `Enzyme` may have been incorrectly updated in the v0.2 release branch given that compatibility is still indicated to be [with v0.11 on `master`](https://github.com/TuringLang/AdvancedVI.jl/blob/e42d4230cc5276e52b414d203435827a7105b67c/Project.toml#L45). I'm running into a situation where I cannot resolve an environment that happens to pull in `Enzyme` for different packages due to this restriction.

I hope it's okay to bump this `compat` back down so we're able to resolve environments like this with the v0.2 release branch. I have completely dropped the v0.12 compatibility here as it's also not marked as compatible on `master` as mentioned above.

### CODE REVIEW

**Comment by Red-Portal** [comment]
I actually wonder if we want to restrict the compat bound for `Enzyme` at all given that we don't test on `Enzyme`. @torfjelde  How about just removing the compat bound entirely?

**Comment by bauglir** [comment]
> How about just removing the compat bound entirely?

I would be fine with either, but I'm not sure whether automerge on the General registry requires `compat`s to be defined for weak dependencies as it does for regular dependencies. If it does, it's probably easier to maintain the `compat` as otherwise all releases of this package would have to get manually merged.

**Comment by Red-Portal** [comment]
Okay, let me first check that.

**Comment by bauglir** [comment]
From a quick glance at the automerge guidelines it looks like the `compat` requirements [are (currently) only applied to strict dependencies](https://github.com/JuliaRegistries/RegistryCI.jl/blob/0e48cdea4b9f5198f1a90f5b5d5504458c6051d7/src/AutoMerge/guidelines.jl#L92) and not to weak dependencies.

[At the moment](https://github.com/JuliaRegistries/RegistryCI.jl/blob/0e48cdea4b9f5198f1a90f5b5d5504458c6051d7/src/AutoMerge/guidelines.jl) the aren't any references to weak dependencies in automerge guidelines. So it looks like it might be okay to not include a `compat` from that perspective at least.

**Comment by Red-Portal** [comment]
I asked around, and authorities do say that compat rules are also enforced to weakdeps. So even if it is not enforced, I think just bumping the bound down would be the formal solution.

**Comment by bauglir** [comment]
Sounds good to me.

**Pull request merged**
