### PR TITLE
Fix `Enzyme` tests on older Julia versions

### PR DESCRIPTION
**Pull request by Red-Portal**

### CODE REVIEW

**Comment by Red-Portal** [comment]
@yebai  Hi Hong, this is a PR fixing the tests failing on 1.7 due to Enzyme. Once the new 1.10 Julia LTS officially lands, I think we could just drop the 1.7 nonsense altogether. Do you agree?

**Comment by Red-Portal** [comment]
@yebai May I merge this PR? Or should I wait until @willtebbutt takes a look?

**Comment by willtebbutt** [comment]
This is much cleaner!

Would it be possible to simplify further and have only a single definition of the backends being used, rather than defining the collection the same way in multiple places? e.g. define a single `ad_backends` variable in `test/runtests.jl`, and use that everywhere? You might have to do something specific for the DistributionsAD tests, since it looks like ReverseDiff doesn't work for those tests, but everything else should be simplified.

**Comment by Red-Portal** [comment]
@willtebbutt I think that defining the set of AD tests used in each file makes it explicit what AD framework is supported and which is not. For now, except for `DistributionsAD`, most AD frameworks are adequately supported, but this might change in the future. For instance, newer AD frameworks could come up that are not compatible with certain functionalities in `AdvancedVI`.

**Review by willtebbutt — APPROVED** [review]
Okay. This makes sense to me. I'm happy for this to be merged.

**Comment by Red-Portal** [comment]
Thanks for the discussion!

**Pull request merged**
